### PR TITLE
Set News View to use Search API cache tags

### PR DESCRIPTION
**Pull request by omahm**

### CODE REVIEW

**Comment by soda736** [comment]
LG should we implement this in publications search API also?

**Comment by omahm** [comment]
> LG should we implement this in publications search API also?

Anywhere you use the Search API as a datasource in a View and you want caching, you should use the Search API tag or time options.

**Review by ooneill547 — APPROVED** [review]
Looks good

**Review by DuttonMa — APPROVED** [review]
LGTM

**Pull request merged**
