### PR TITLE
Improved link functionality in CKEditor

### PR DESCRIPTION
**Pull request by ooneill547**
- Installed Noreferrer and Linkit modules.
- Linkit profile allows user to link to internal content and taxonomies. 
- It also includes the option to add a title and lets the user decide whether the link should open in a new window/tab.
- Link description has been edited using the custom cybersecurity_common module.

### CODE REVIEW

**Review by omahm — COMMENTED** [review]
Looks good but with small changes like this I'd be tempted to create a 'cybersecurity_common' module as a place to dump small tweaks and changes instead of individual modules.

**Review by omahm — COMMENTED** [review]
Good job 👍 just need to delete the old module.

**Comment by ooneill547** [comment]
It must have got included again when I ran git pull, it should be gone now

**Review by johangant — APPROVED** [review]
Looks good, nice one

**Review by omahm — APPROVED** [review]
Nice one, GTG

**Pull request merged**
