### PR TITLE
Add responsive image style as a class to the picture tag

### PR DESCRIPTION
**Pull request by ooneill547**

### CODE REVIEW

**Comment by ooneill547** [comment]
I'm not sure whether it would be tidier to do this with a preprocess function rather than adding it in the twig template?

**Comment by omahm** [comment]
> I'm not sure whether it would be tidier to do this with a preprocess function rather than adding it in the twig template?

If in doubt, I'd add it as a pre-process

**Review by johangant — CHANGES_REQUESTED** [review]
So I think this _does_ what it needs to do, but I have some comments on _how_ it does this with regards to future maintenance.

> I'm not sure whether it would be tidier to do this with a preprocess function rather than adding it in the twig template?

I don't think there's a strong reason either way as a general approach, but one thing that does stand out is the fixed class rather than having something you can pass in via attributes. As that stands, it might stifle any preprocess code in the future. Example:

`<picture class="img_style_{{ responsive_image_style_id }}">`

might want to look something closer to:

`<picture class="{{ classes }}">` with classes being passed into the template like any other attributes. You'll find examples of this in almost all preprocess hooks for any themeable (anything registered in hook_theme) things in Drupal: https://www.drupal.org/docs/8/theming-drupal-8/modifying-attributes-in-a-theme-file

Generally speaking, if you haven't already got an array key called 'attributes' in the render array you can create one and have something like:

```
/**
 * Implements hook_preprocess_responsive_image().
 */
function cybersecurity_preprocess_responsive_image(&$variables) {
  $variables['attributes']['classes'] = ['head', 'shoulders', 'knees', 'toes'];
}
```

This approach means any module or theme can implement that hook and manipulate the render array right up to the point where it's handed across to the Twig template for rendering.

NB: I've written all the above off-the-cuff so some inspection of the variables will probably be needed to ensure it all lines up.

**Review by johangant — APPROVED** [review]
Nailed it 👍

**Pull request merged**
